---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bumdesad/public_html/
    - /bin/cp kuis_evaluasi_bumdesa.html $DEPLOYPATH
    - /bin/cp api_kuis.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp app/core/App.php $DEPLOYPATH/app/core/
    - /bin/cp app/controllers/Kuis.php $DEPLOYPATH/app/controllers/
    - /bin/cp app/views/home/index.php $DEPLOYPATH/app/views/home/
    - /bin/cp aplikasi_kurasi_bumdesa_simpleakunting_linked.html $DEPLOYPATH
    - /bin/cp public/kuis_evaluasi_bumdesa.html $DEPLOYPATH/public/
    - /bin/cp public/api_kuis.php $DEPLOYPATH/public/
